# Generated by Django 2.0.2 on 2018-02-19 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
