# Generated by Django 2.0.2 on 2018-02-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_business_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=125)),
                ('descrip', models.TextField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('item_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Business')),
            ],
        ),
    ]
